name: Build and Release

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: lukka/get-cmake@latest 

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Archive Xinput1.4.dll
      if: always()
      run: |
        mkdir -p build/artifacts
        cp build/bin/Release/Xinput1_4.dll build/artifacts/Xinput1_4.dll

    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/artifacts/Xinput1_4.dll
        asset_name: Xinput1_4.dll
        asset_content_type: application/octet-stream